### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by tmpfs** [mpc-sdk/multi-factor-accounts#24]
* [x] Stabilize and audit for snap code (@tmpfs)
* [ ] Release of `cggmp-threshold-ecdsa` with new sub-protocols and ZK proofs (@ivokub)
* [ ] Update sdk framework with new driver for CGGMP implementation (@tmpfs)
* [ ] Test DKG and signing in staging release (@tmpfs & @ivokub)
* [ ] Provide git commit hash for audit of dapp code (@tmpfs)
* [ ] Provide git commit hash for audit of `cggmp-threshold-ecdsa` protocol code (@ivokub)
* [ ] Update UI to support CGGMP protocol driver
* [x] Support user-defined backend server URL (#21)
* [ ] User acceptance testing
